version: '2'

services:
  postgres:
    image: 'postgres:13.2'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:6.2.1-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "goalgetter.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/goalgetter'
    ports:
      - '8000:8000'

volumes:
  postgres:
  redis:
